name: Publish Docker container

on:
  push:
    # Publish `master|main` as Docker `latest` image.
    branches:
      - master
      - main

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

  # Run tests for any PRs.
  pull_request:

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: foreveraward    # Add your cluster name here.
  GKE_ZONE: us-west1   # Add your cluster zone here.


jobs:
  push_to_ghcr:
    name: Push to ghcr.io/dathan/go-upload-bridge-pinata:latest
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      
      # Setup gcloud CLI
      - uses: google-github-actions/setup-gcloud@94337306dda8180d967a56932ceb4ddcf01edae7
        with:
          service_account_key: ${{ secrets.GKE_SA_KEY }}
          project_id: ${{ secrets.GKE_PROJECT }}
      # Get the GKE credentials so we can deploy to the cluster
      - uses: google-github-actions/get-gke-credentials@fb08709ba27618c31c09e014e1d8364b02e5042e
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.GKE_ZONE }}
          credentials: ${{ secrets.GKE_SA_KEY }}


      - name: Build & push Docker image
        uses: mr-smithers-excellent/docker-build-push@v5
        id: docker
        with:
          image: go-upload-bridge-pinata
          registry: ghcr.io
          tags: v1, latest, ${{ github.run_id }}
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Deploy
        run: |-
          curl https://baltocdn.com/helm/signing.asc | sudo apt-key add -
          sudo apt-get install apt-transport-https --yes
          echo "deb https://baltocdn.com/helm/stable/debian/ all main" | sudo tee /etc/apt/sources.list.d/helm-stable-debian.list
          sudo apt-get update
          sudo apt-get install helm
          sed -i 's/autothis/${{ github.run_id }}/g' ./helm/go-upload-bridge-pinata/Chart.yaml
          helm upgrade go-upload-bridge-pinata ./helm/go-upload-bridge-pinata/ --set image.tag=${{ github.run_id }}
          helm ls

